root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/vicky-admin ./cmd/vicky-admin"
  bin = "./tmp/vicky-admin"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "migrations"]
  delay = 1000

[log]
  time = false
